### ISSUE TITLE
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by tbakil** [Leon-Sander/local_multimodal_ai_chat#26]
I get this error I could not find a solution for it! Can any one help me please!!

$ python3 test.py
Traceback (most recent call last):
  File "/home/bakil/demo_bitirme/local_multimodal_ai_chat/test.py", line 4, in <module>
    vector_db = load_vectordb(create_embeddings())
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/bakil/demo_bitirme/local_multimodal_ai_chat/llm_chains.py", line 25, in create_embeddings
    return HuggingFaceInstructEmbeddings(model_name=embeddings_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bakil/demo_bitirme/local_multimodal_ai_chat/chat_venv/lib/python3.11/site-packages/langchain_community/embeddings/huggingface.py", line 158, in __init__
    self.client = INSTRUCTOR(
                  ^^^^^^^^^^^
  File "/home/bakil/demo_bitirme/local_multimodal_ai_chat/chat_venv/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 194, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

**Comment by eekarot** [comment]
you can solve the problem by: pip install sentence_transformers==2.2.2

**Comment by Paramjethwa** [comment]
> you can solve the problem by: pip install sentence_transformers==2.2.2

worked thanks dude!! god bless you
